apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-json
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webapp 
        image: acrromm.azurecr.io/webapp:1.1 
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: secretpass

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-entrypoint
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 5000
    
